---
# SPDX-FileCopyrightText: Â© 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration

"on":
  - "push"
  - "pull_request"

env:
  npm_config_cache: /tmp/npm-cache

jobs:
  build:
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node-version:
          # Support policy: We support every Node.js version that is still "maintained".
          # See: https://nodejs.org/en/about/releases/
          - "18.x"
          - "20.x"
          - "22.x"
          - "23.x"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - id: npm-cache
        name: Restore npm cache
        uses: actions/cache@v4
        with:
          key: npm-cache-${{ github.ref_name }}
          path: ${{ env.npm_config_cache }}

      - name: Install dependencies
        run: make dependencies-get

      - name: Run full test suite
        run: make check-full
